ZenBlog/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ZenBlog.Core.Common;
using ZenBlog.Core.DTOs;
using ZenBlog.Core.Repositories;
using ZenBlog.DataLayer.Models;

namespace ZenBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private ISettingRepository _settingRepository;
        private IUserRepository _userRepository;

        public HomeController(ISettingRepository settingRepository, IUserRepository userRepository)
        {
            _settingRepository = settingRepository;
            _userRepository = userRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _settingRepository.ShowCount());
        }

        // GET: UserController/Profile/5
        public async Task<ActionResult> Profile()
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = await _userRepository.GetById(userId);
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                FullName = user.FullName,
                phone = user.phone,
                Email = user.Email,
                Role = user.Role,
                Password = user.Password,
                OldImage = user.Image
            });
        }

        // POST: UserController/Profile/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Profile([Bind("FullName,phone,Email,Password,OldImage,Image")] EditUserViewModel editUser)
        {
            /*
             Id,FullName,phone,Email,Role,Password,OldImage,Image
             */
            if (!ModelState.IsValid)
            {
                return View(editUser);
            }

            await _userRepository.Update(editUser);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Setting() => View(await _settingRepository.GetSetting());

        [HttpPost]
        public async Task<IActionResult> Setting(Setting setting)
        {
            if (!ModelState.IsValid)
            {
                return View(setting);
            }
            var result =await _settingRepository.ChangeSetting(setting);
            if (!result)
            {
                ModelState.AddModelError("AboutUs", "اطلاعات را به درستی وارد کنید");
                return View();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ZenBlog/Areas/Student/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ZenBlog.Core.Common;
using ZenBlog.Core.DTOs;
using ZenBlog.Core.Repositories;
using ZenBlog.DataLayer.Models;

namespace ZenBlog.Areas.Student.Controllers
{
    [Area("Student")]
    public class HomeController : Controller
    {
        private ISettingRepository _settingRepository;
        private IUserRepository _userRepository;

        public HomeController(ISettingRepository settingRepository, IUserRepository userRepository)
        {
            _settingRepository = settingRepository;
            _userRepository = userRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _settingRepository.ShowCount());
        }

        // GET: UserController/Profile/5
        public async Task<ActionResult> Profile()
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = await _userRepository.GetById(userId);
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                FullName = user.FullName,
                phone = user.phone,
                Email = user.Email,
                Role = user.Role,
                Password = user.Password,
                OldImage = user.Image
            });
        }

        // POST: UserController/Profile/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Profile([Bind("Id,FullName,phone,Email,Role,Password,OldImage,Image")] EditUserViewModel editUser)
        {
            /*
             Id,FullName,phone,Email,Role,Password,OldImage,Image
             */
            if (!ModelState.IsValid)
            {
                return View(editUser);
            }
            
            await _userRepository.Update(editUser);
            return RedirectToAction(nameof(Index));
        }


    }
}

ZenBlog/Areas/Teacher/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ZenBlog.Core.Common;
using ZenBlog.Core.DTOs;
using ZenBlog.Core.Repositories;
using ZenBlog.DataLayer.Models;

namespace ZenBlog.Areas.Teacher.Controllers
{
    [Area("Teacher")]
    public class HomeController : Controller
    {
        private ISettingRepository _settingRepository;
        private IUserRepository _userRepository;

        public HomeController(ISettingRepository settingRepository, IUserRepository userRepository)
        {
            _settingRepository = settingRepository;
            _userRepository = userRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _settingRepository.ShowCount());
        }

        // GET: UserController/Profile/5
        public async Task<ActionResult> Profile()
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = await _userRepository.GetById(userId);
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                FullName = user.FullName,
                phone = user.phone,
                Email = user.Email,
                Role = user.Role,
                Password = user.Password,
                OldImage = user.Image
            });
        }

        // POST: UserController/Profile/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Profile([Bind("Id,FullName,phone,Email,Role,Password,OldImage,Image")] EditUserViewModel editUser)
        {
            /*
             Id,FullName,phone,Email,Role,Password,OldImage,Image
             */
            if (!ModelState.IsValid)
            {
                return View(editUser);
            }
            
            await _userRepository.Update(editUser);
            return RedirectToAction(nameof(Index));
        }


    }
}

ZenBlog/Components/CategoryIndexViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Components
{
    public class CategoryIndexViewComponent : ViewComponent
    {
        private ICategoryRepository _categoryRepository;

        public CategoryIndexViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryRepository.GetCategoryForIndex();
            return View("/Views/Components/CategoryIndexViewComponent.cshtml", categories);
        }
    }
}

ZenBlog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ZenBlog.Core.Repositories;
using ZenBlog.Models;

namespace ZenBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IPostRepository _postRepository;
        private ISettingRepository _settingRepository;

        public HomeController(ILogger<HomeController> logger, IPostRepository postRepository, ISettingRepository settingRepository)
        {
            _logger = logger;
            _postRepository = postRepository;
            _settingRepository = settingRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(new IndexViewModel()
            {
                Posts = await _postRepository.GetPostSlider(),
            });
        }

        [Route("AboutUs")]
        public async Task<IActionResult> AboutUs()
        {
            return View(await _settingRepository.GetSetting());
        }

        [Route("ContactUs")]
        public async Task<IActionResult> ContactUsAsync()
        {
            return View(await _settingRepository.GetSetting());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ZenBlog/Views/Home/AboutUs.cshtml
@model Setting
@{
    ViewData["Title"] = "درباره ما";
}


<main id="main">
    <section>
        <div class="container aos-init aos-animate" data-aos="fade-up">
            <div class="row">
                <div class="col-lg-12 text-center mb-5">
                    <h1 class="page-title">درباره ما</h1>
                </div>
            </div>

            <div class="row mb-5">

                <div class="d-md-flex post-entry-2 half">
                    <a href="#" class="me-4 thumbnail">
                        <img src="/Blog Template/assets/img/post-landscape-2.jpg" alt="" class="img-fluid">
                    </a>
                    <div class="pe-md-5 mt-4 mt-md-0">
                        <div class="post-meta mt-4">درباره</div>
                        <h2 class="mb-4 display-4">ZenBlog</h2>
                        <p>
                            @Html.Raw(Model.AboutUs)
                        </p>
                    </div>
                </div>

            </div>

            <div class="row gy-4">

                <div class="col-md-4">
                    <div class="info-item">
                        <i class="bi bi-geo-alt"></i>
                        <h3>آدرس</h3>
                        <address>@Model.Address</address>
                    </div>
                </div><!-- End Info Item -->

                <div class="col-md-4">
                    <div class="info-item info-item-borders">
                        <i class="bi bi-phone"></i>
                        <h3>تلفن</h3>
                        <p><a href="tel:@Model.Phones">@Model.Phones</a></p>
                    </div>
                </div><!-- End Info Item -->

                <div class="col-md-4">
                    <div class="info-item">
                        <i class="bi bi-envelope"></i>
                        <h3>ایمیل</h3>
                        <p><a href="mailto:@(Model.Email)">@Model.Email</a></p>
                    </div>
                </div><!-- End Info Item -->

            </div>
        </div>
    </section>
    
    <section>
        <div class="container aos-init aos-animate" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-12 text-center mb-5">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <h2 class="display-4">تیم توسعه دهنده</h2>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 text-center mb-5">
                    <img src="/Blog Template/assets/img/69380758.png" alt="" class="img-fluid rounded-circle w-50 mb-4">
                    <h4>محمد صدرا برومند</h4>
                    <span class="d-block mb-3 text-uppercase">سازنده</span>
                    <p>FullStack Developer</p>
                </div>

            </div>
        </div>
    </section>

</main>

ZenBlog/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "تماس با ما";
}

<main id="main">
    <section id="contact" class="contact mb-5">
        <div class="container aos-init aos-animate" data-aos="fade-up">

            <div class="row">
                <div class="col-lg-12 text-center mb-5">
                    <h1 class="page-title">تماس با ما</h1>
                </div>
            </div>


            <div class="form mt-3">
                <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <input type="text" name="name" class="form-control" id="name" placeholder="نام شما" required="">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="email" class="form-control" name="email" id="email" placeholder="ایمیل" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="موضوع" required="">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="message" rows="5" placeholder="پیام" required=""></textarea>
                    </div>
                    <div class="my-3">
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">ارسال پیام</button></div>
                </form>
            </div><!-- End Contact Form -->

        </div>
    </section>

</main>

ZenBlog/Views/Home/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "صفحه اصلی";
}

<main id="main">

    <partial name="SliderPartialView" model="Model.Posts"/>
    <!-- ======= Post Grid Section ======= -->
    <section id="posts" class="posts">
        <div class="container" data-aos="fade-up">
            <div class="row g-5">
                <div class="col-lg-4">
                    <div class="post-entry-1 lg">
                        <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-1.jpg" alt="" class="img-fluid"></a>
                        <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                        <h2><a href="single-post.html">11 Work From Home Part-Time Jobs You Can Do Now</a></h2>
                        <p class="mb-4 d-block">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero temporibus repudiandae, inventore pariatur numquam cumque possimus exercitationem? Nihil tempore odit ab minus eveniet praesentium, similique blanditiis molestiae ut saepe perspiciatis officia nemo, eos quae cumque. Accusamus fugiat architecto rerum animi atque eveniet, quo, praesentium dignissimos</p>

                        <div class="d-flex align-items-center author">
                            <div class="photo"><img src="/Blog Template/assets/img/person-1.jpg" alt="" class="img-fluid"></div>
                            <div class="name">
                                <h3 class="m-0 p-0">Cameron Williamson</h3>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-lg-8">
                    <div class="row g-5">
                        <div class="col-lg-4 border-start custom-border">
                            <div class="post-entry-1">
                                <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-2.jpg" alt="" class="img-fluid"></a>
                                <div class="post-meta"><span class="date">Sport</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                <h2><a href="single-post.html">Let’s Get Back to Work, New York</a></h2>
                            </div>
                            <div class="post-entry-1">
                                <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-5.jpg" alt="" class="img-fluid"></a>
                                <div class="post-meta"><span class="date">Food</span> <span class="mx-1">&bullet;</span> <span>Jul 17th '22</span></div>
                                <h2><a href="single-post.html">How to Avoid Distraction and Stay Focused During Video Calls?</a></h2>
                            </div>
                            <div class="post-entry-1">
                                <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-7.jpg" alt="" class="img-fluid"></a>
                                <div class="post-meta"><span class="date">Design</span> <span class="mx-1">&bullet;</span> <span>Mar 15th '22</span></div>
                                <h2><a href="single-post.html">Why Craigslist Tampa Is One of The Most Interesting Places On the Web?</a></h2>
                            </div>
                        </div>
                        <div class="col-lg-4 border-start custom-border">
                            <div class="post-entry-1">
                                <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-3.jpg" alt="" class="img-fluid"></a>
                                <div class="post-meta"><span class="date">Business</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                <h2><a href="single-post.html">6 Easy Steps To Create Your Own Cute Merch For Instagram</a></h2>
                            </div>
                            <div class="post-entry-1">
                                <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-6.jpg" alt="" class="img-fluid"></a>
                                <div class="post-meta"><span class="date">Tech</span> <span class="mx-1">&bullet;</span> <span>Mar 1st '22</span></div>
                                <h2><a href="single-post.html">10 Life-Changing Hacks Every Working Mom Should Know</a></h2>
                            </div>
                            <div class="post-entry-1">
                                <a href="single-post.html"><img src="/Blog Template/assets/img/post-landscape-8.jpg" alt="" class="img-fluid"></a>
                                <div class="post-meta"><span class="date">Travel</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                <h2><a href="single-post.html">5 Great Startup Tips for Female Founders</a></h2>
                            </div>
                        </div>

                        <!-- Trending Section -->
                        <div class="col-lg-4">

                            <div class="trending">
                                <h3>مشهورترین ها</h3>
                                <ul class="trending-post">
                                    <li>
                                        <a href="single-post.html">
                                            <span class="number">1</span>
                                            <h3>The Best Homemade Masks for Face (keep the Pimples Away)</h3>
                                            <span class="author">Jane Cooper</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="single-post.html">
                                            <span class="number">2</span>
                                            <h3>17 Pictures of Medium Length Hair in Layers That Will Inspire Your New Haircut</h3>
                                            <span class="author">Wade Warren</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="single-post.html">
                                            <span class="number">3</span>
                                            <h3>13 Amazing Poems from Shel Silverstein with Valuable Life Lessons</h3>
                                            <span class="author">Esther Howard</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="single-post.html">
                                            <span class="number">4</span>
                                            <h3>9 Half-up/half-down Hairstyles for Long and Medium Hair</h3>
                                            <span class="author">Cameron Williamson</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="single-post.html">
                                            <span class="number">5</span>
                                            <h3>Life Insurance And Pregnancy: A Working Mom’s Guide</h3>
                                            <span class="author">Jenny Wilson</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div> <!-- End Trending Section -->
                    </div>
                </div>

            </div> <!-- End .row -->
        </div>
    </section> <!-- End Post Grid Section -->

    @await Component.InvokeAsync("CategoryIndex")

</main>
<!-- End #main -->