ZenBlog/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ZenBlog.Core.DTOs;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private IPostRepository _postRepository;
        private ICategoryRepository _categoryRepository;
        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
        }

        // GET: PostController
        [Route("Admin/Posts/{pageNumber?}")]
        public async Task<ActionResult> Index(int pageNumber = 0, int pageSize = 5)
        {
            ViewData["pageNumber"] = pageNumber;
            return View(await _postRepository.GetAllPost(pageNumber, pageSize));
        }

        // GET: PostController/Details/5
        //public async Task<ActionResult> Details(int id)
        //{
        //    return View(await _postRepository.GetPostById(id));
        //}

        // GET: PostController/Create
        public async Task<ActionResult> Create()
        {
            var categories = await _categoryRepository.GetAllCategoryAsync();
            return View(new AddEditPostViewModel()
            {
                Category = categories
            });
        }

        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddEditPostViewModel addEditPost)
        {
            if (!ModelState.IsValid)
            {
                return View(addEditPost);
            }
            addEditPost.UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            await _postRepository.Insert(addEditPost);
            return RedirectToAction(nameof(Index));
        }

        // GET: PostController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _postRepository.GetPostForUpdate(id));
        }

        // POST: PostController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AddEditPostViewModel addEditPost)
        {
            if (!ModelState.IsValid)
            {
                return View(addEditPost);
            }
            await _postRepository.Update(addEditPost);
            return RedirectToAction(nameof(Index));
        }

        // GET: PostController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _postRepository.GetPostById(id));
        }

        // POST: PostController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(float id)
        {
            await _postRepository.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ZenBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        [Route("Category/{categoryTitle}/{categoryId}/{pageNumber?}")]
        public async Task<IActionResult> ShowCategory(string categoryTitle, int categoryId, int pageNumber = 0, int pageSize = 5)
        {
            ViewData["categoryTitle"] = categoryTitle;
            var result = await _categoryRepository
                .GetCategory(categoryId, pageNumber, pageSize);
            return View(result);
        }
    }
}

ZenBlog/Areas/Teacher/Views/Shared/_LayoutAdmin.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html lang="en" class="loading">

<!-- Mirrored from pixinvent.com/demo/sadra-bootstrap-admin-dashboard-template/demo-2/dashboard-ecommerce.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 20 Sep 2018 15:01:26 GMT -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="sadra admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, sadra admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>پنل استاد - @ViewData["Title"]</title>
    <partial name="_Styles" />
</head>
<body data-col="2-columns" class=" 2-columns ">
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <div class="wrapper">


        <div data-active-color="white" data-background-color="aqua-marine" data-image="/AdminTemplate/img/sidebar-bg/02.jpg" class="app-sidebar">
            <div class="sidebar-header">
                <div class="logo clearfix">
                    <a asp-action="Index" class="logo-text float-right">
                        <div class="logo-img"><img src="/AdminTemplate/img/logo.png" alt="sadra Logo" /></div><span class="text align-middle">مدیریت</span>
                    </a><a id="sidebarToggle" href="javascript:;" class="nav-toggle d-none d-sm-none d-md-none d-lg-block"><i data-toggle="expanded" class="ft-disc toggle-icon"></i></a><a id="sidebarClose" href="javascript:;" class="nav-close d-block d-md-block d-lg-none d-xl-none"><i class="ft-circle"></i></a>
                </div>
            </div>
            <div class="sidebar-content">
                <div class="nav-container">
                    <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
                        <li class="has-sub nav-item">
                            <a href="#">
                                <i class="icon-home"></i><span data-i18n="" class="menu-title">داشبورد</span>
                                @*<span class="tag badge badge-pill badge-danger mt-1">2</span>*@
                            </a>
                            <ul class="menu-content">
                               
                                <li>
                                    <a asp-controller="Post" asp-action="Index" class="menu-item">لیست پست ها</a>
                                </li>
                                <li>
                                    <a asp-controller="Category" asp-action="Index" class="menu-item">لیست گروه ها</a>
                                </li>
                            </ul>
                        </li>
                        @*<li class=" nav-item">
                                <a href="https://pixinvent.ticksy.com/"><i class="icon-support"></i><span data-i18n="" class="menu-title">پشتیبانی</span></a>
                            </li>*@
                        <li class=" nav-item">
                            <a asp-area="Teacher" asp-controller="Home" asp-action="Profile"><i class="icon-user"></i><span data-i18n="" class="menu-title">پروفایل</span></a>
                        </li>
                        <li class=" nav-item">
                            <a href="/"><i class="icon-screen-desktop"></i><span data-i18n="" class="menu-title">برگشت به صفحه اصلی</span></a>
                        </li>
                        <li class=" nav-item">
                            <a href="/Logout"><i class="icon-logout"></i><span data-i18n="" class="menu-title">خروج</span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="sidebar-background"></div>
        </div>


        <nav class="navbar navbar-expand-lg navbar-light bg-faded">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" data-toggle="collapse" class="navbar-toggle d-lg-none float-right"><span class="sr-only">تغییر ناوبری </span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><span class="d-lg-none navbar-right navbar-collapse-toggle"><a class="open-navbar-container"><i class="ft-more-vertical"></i></a></span><a id="navbar-fullscreen" href="javascript:;" class="ml-2 display-inline-block apptogglefullscreen">
                        <i class="ft-maximize blue-grey darken-4 toggleClass"></i>
                        <p class="d-none">تمام صفحه</p>
                    </a>


                </div>
                <div class="navbar-container">
                    <div id="navbarSupportedContent" class="collapse navbar-collapse">
                        <ul class="navbar-nav">

                            <li class="dropdown nav-item mr-0">
                                <a id="dropdownBasic3" href="#" data-toggle="dropdown" class="nav-link position-relative dropdown-user-link dropdown-toggle">
                                    <span class="avatar avatar-online"><img id="navbar-avatar" src="@User.FindFirstValue(ClaimTypes.Actor)" alt="avatar" /></span>
                                    <p class="d-none">تنظیمات کاربر</p>
                                </a>
                                <div aria-labelledby="dropdownBasic3" class="dropdown-menu dropdown-menu-left">
                                    <div class="arrow_box_right">
                                        <a asp-controller="Home" asp-action="Profile" class="dropdown-item py-1">
                                            <i class="ft-edit ml-2"></i><span>پروفایل من</span>
                                        </a>
                                        <a href="/" class="dropdown-item py-1">
                                            <i class="ft-home ml-2"></i><span>برگشت به سایت اصلی</span>
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a href="/Logout" class="dropdown-item">
                                            <i class="ft-power ml-2"></i><span>خروج</span>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div class="main-panel">
            <div class="main-content">
                <div class="content-wrapper">
                    <div class="container-fluid">

                        @RenderBody()
                    </div>
                </div>
            </div>

            <footer class="footer footer-static footer-light">
                <p class="clearfix text-muted text-center px-2"><span>&copy; 2022 کپی رایت  <span class="text-bold-800 info darken-2">Sadra</span>,همه حقوق محفوظ است </span></p>
            </footer>

        </div>
    </div>
    <!-- ////////////////////////////////////////////////////////////////////////////-->

    <partial name="_Scripts" />
    @await RenderSectionAsync("Scripts", false)
</body>

<!-- Mirrored from pixinvent.com/demo/sadra-bootstrap-admin-dashboard-template/demo-2/dashboard-ecommerce.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 20 Sep 2018 15:01:26 GMT -->
</html>

ZenBlog/Areas/Teacher/Views/Shared/_Scripts.cshtml
<!-- BEGIN VENDOR JS-->
<script src="/AdminTemplate/vendors/js/core/jquery-3.3.1.min.js"></script>
@*<script src="/AdminTemplate/js/persian-datepicker.min.js"></script>*@
<script src="/AdminTemplate/vendors/js/core/popper.min.js"></script>
<script src="/AdminTemplate/vendors/js/core/bootstrap.min.js"></script>
<script src="/AdminTemplate/vendors/js/perfect-scrollbar.jquery.min.js"></script>
<script src="/AdminTemplate/vendors/js/prism.min.js"></script>
<script src="/AdminTemplate/vendors/js/jquery.matchHeight-min.js"></script>
<script src="/AdminTemplate/vendors/js/screenfull.min.js"></script>
<script src="/AdminTemplate/vendors/js/pace/pace.min.js"></script>
<!-- BEGIN VENDOR JS-->
<!-- BEGIN PAGE VENDOR JS-->
@*<script src="/AdminTemplate/vendors/js/chartist.min.js"></script>*@
<!-- END PAGE VENDOR JS-->
<!-- BEGIN sadra JS-->
<script src="/AdminTemplate/js/app-sidebar.js"></script>
<script src="/AdminTemplate/js/notification-sidebar.js"></script>
<script src="/AdminTemplate/js/customizer.js"></script>
<script src="/AdminTemplate/js/customizer.js"></script>
<!-- END sadra JS-->
<!-- BEGIN PAGE LEVEL JS-->
@*<script src="/AdminTemplate/js/dashboard-ecommerce.js"></script>*@
<!-- END PAGE LEVEL JS-->

ZenBlog/Areas/Teacher/Views/Shared/_Styles.cshtml
<link rel="apple-touch-icon" sizes="60x60" href="/AdminTemplate/img/ico/apple-icon-60.html">
<link rel="apple-touch-icon" sizes="76x76" href="/AdminTemplate/img/ico/apple-icon-76.html">
<link rel="apple-touch-icon" sizes="120x120" href="/AdminTemplate/img/ico/apple-icon-120.html">
<link rel="apple-touch-icon" sizes="152x152" href="/AdminTemplate/img/ico/apple-icon-152.html">
@*<link rel="shortcut icon" type="image/x-icon" href="https://pixinvent.com/demo/sadra-bootstrap-admin-dashboard-template/app-assets/img/ico/favicon.ico">*@
<link rel="shortcut icon" type="image/png" href="/AdminTemplate/img/ico/favicon-32.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-touch-fullscreen" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
@*<link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900%7CMontserrat:300,400,500,600,700,800,900" rel="stylesheet">*@
<link rel="stylesheet" type="text/css" href="/AdminTemplate/fonts/feather/style.min.css">
<link rel="stylesheet" type="text/css" href="/AdminTemplate/fonts/simple-line-icons/style.css">
<link rel="stylesheet" type="text/css" href="/AdminTemplate/fonts/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/AdminTemplate/vendors/css/perfect-scrollbar.min.css">
<link rel="stylesheet" type="text/css" href="/AdminTemplate/vendors/css/prism.min.css">
<link rel="stylesheet" type="text/css" href="/AdminTemplate/vendors/css/chartist.min.css">
<link rel="stylesheet" type="text/css" href="/AdminTemplate/css/app.css">