ZenBlog/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ZenBlog.Core.DTOs;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private IPostRepository _postRepository;
        private ICategoryRepository _categoryRepository;
        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
        }

        // GET: PostController
        [Route("Admin/Posts/{pageNumber?}")]
        public async Task<ActionResult> Index(int pageNumber = 0, int pageSize = 5)
        {
            ViewData["pageNumber"] = pageNumber;
            return View(await _postRepository.GetAllPost(pageNumber, pageSize));
        }

        // GET: PostController/Details/5
        //public async Task<ActionResult> Details(int id)
        //{
        //    return View(await _postRepository.GetPostById(id));
        //}

        // GET: PostController/Create
        public async Task<ActionResult> Create()
        {
            var categories = await _categoryRepository.GetAllCategoryAsync();
            return View(new AddEditPostViewModel()
            {
                Category = categories
            });
        }

        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddEditPostViewModel addEditPost)
        {
            if (!ModelState.IsValid)
            {
                return View(addEditPost);
            }
            addEditPost.UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            await _postRepository.Insert(addEditPost);
            return RedirectToAction(nameof(Index));
        }

        // GET: PostController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _postRepository.GetPostForUpdate(id));
        }

        // POST: PostController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AddEditPostViewModel addEditPost)
        {
            if (!ModelState.IsValid)
            {
                return View(addEditPost);
            }
            await _postRepository.Update(addEditPost);
            return RedirectToAction(nameof(Index));
        }

        // GET: PostController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _postRepository.GetPostById(id));
        }

        // POST: PostController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(float id)
        {
            await _postRepository.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ZenBlog/Components/HeaderViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        private ICategoryRepository _categoryRepository;

        public HeaderViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryRepository.GetAllCategoryAsync();
            return View("/Views/Components/HeaderViewComponent.cshtml",categories);
        }
    }
}

ZenBlog/Views/Shared/SliderPartialView.cshtml
@model IEnumerable<Post>
<!-- ======= Hero Slider Section ======= -->
<section id="hero-slider" class="hero-slider">
    <div class="container-md" data-aos="fade-in">
        <div class="row">
            <div class="col-12">
                <div class="swiper sliderFeaturedPosts">
                    <div class="swiper-wrapper">

                        @foreach (var item in Model)
                        {
                            <div class="swiper-slide">
                                <a  asp-controller="Post"
                                    asp-action="Post"
                                    asp-route-postId="@item.Id"
                                    asp-route-postTitle="@item.Title"
                                    asp-route-categoryTitle="@item.Category.Title"
                                    class="img-bg d-flex align-items-end" style="background-image: url('@(item.Image.Replace(@"\","/"))');">
                                    <div class="img-bg-inner">
                                        <h2>@item.Title</h2>
                                        <p>@Html.Raw(item.ShortDescription)</p>
                                    </div>
                                </a>
                            </div>

                        }

                    </div>
                    <div class="custom-swiper-button-next">
                        <span class="bi-chevron-right"></span>
                    </div>
                    <div class="custom-swiper-button-prev">
                        <span class="bi-chevron-left"></span>
                    </div>

                    <div class="swiper-pagination"></div>
                </div>
            </div>
        </div>
    </div>
</section><!-- End Hero Slider Section -->

ZenBlog/Views/Shared/_Layout.cshtml
@using ZenBlog.Components
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - ZenBlog</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <partial name="_Styles" />

</head>

<body>

    @await Component.InvokeAsync("Header")

    @RenderBody()

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">

                <div class="row g-5">
                    <div class="col-lg-4">
                        <h3 class="footer-heading">درباره ZenBlog</h3>
                        <p class="text-white">
                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                        </p>
                        <p><a asp-controller="Home" asp-action="AboutUs" class="footer-link-more">Learn More</a></p>
                    </div>
                    <div class="col-6 col-lg-2">
                        <h3 class="footer-heading">Navigation</h3>
                        <ul class="footer-links list-unstyled">
                            <li><a asp-controller="Home" asp-action="Index"><i class="bi bi-chevron-right"></i> صفحه اصلی</a></li>
                            <li><a asp-controller="Home" asp-action="AboutUs"><i class="bi bi-chevron-right"></i>درباره ما</a></li>
                            <li><a asp-controller="Home" asp-action="ContactUs"><i class="bi bi-chevron-right"></i> تماس با ما</a></li>
                        </ul>
                    </div>


                    <div class="col-lg-4">
                        <h3 class="footer-heading">پست های اخیر</h3>

                        <ul class="footer-links footer-blog-entry list-unstyled">
                            <li>
                                <a href="/" class="d-flex align-items-center">
                                    <img src="/Blog Template/assets/img/post-sq-1.jpg" alt="" class="img-fluid me-3">
                                    <div class="mx-3">
                                        <div class="post-meta d-block text-white"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                        <span class="text-white">5 Great Startup Tips for Female Founders</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="/" class="d-flex align-items-center">
                                    <img src="/Blog Template/assets/img/post-sq-2.jpg" alt="" class="img-fluid me-3">
                                    <div class="mx-3">
                                        <div class="post-meta d-block text-white"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                        <span class="text-white">What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="/" class="d-flex align-items-center">
                                    <img src="/Blog Template/assets/img/post-sq-3.jpg" alt="" class="img-fluid me-3">
                                    <div class="mx-3">
                                        <div class="post-meta d-block text-white"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                        <span class="text-white">Life Insurance And Pregnancy: A Working Mom’s Guide</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="/" class="d-flex align-items-center">
                                    <img src="/Blog Template/assets/img/post-sq-4.jpg" alt="" class="img-fluid me-3">
                                    <div class="mx-3">
                                        <div class="post-meta d-block text-white"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                                        <span class="text-white">How to Avoid Distraction and Stay Focused During Video Calls?</span>
                                    </div>
                                </a>
                            </li>

                        </ul>

                    </div>
                </div>
            </div>
        </div>

        <div class="footer-legal">
            <div class="container">

                <div class="row justify-content-between">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <div class="copyright text-white">
                            © Copyright ZenBlog. All Rights Reserved
                        </div>

                        <div class="credits text-white">
                            Designed by <a href="#">SADRA</a>
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                            <a href="#" class="twitter"><i class="bi bi-twitter text-white"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook text-white"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram text-white"></i></a>
                            <a href="#" class="google-plus"><i class="bi bi-skype text-white"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin text-white"></i></a>
                        </div>

                    </div>

                </div>

            </div>
        </div>

    </footer>

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <partial name="_Scripts" />
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

ZenBlog/Views/Shared/_Scripts.cshtml
<!-- Vendor JS Files -->
<script src="/Blog Template/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/Blog Template/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="/Blog Template/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="/Blog Template/assets/vendor/aos/aos.js"></script>
<script src="/Blog Template/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="/Blog Template/assets/js/main.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
<script src="~/js/site.js" asp-append-version="true"></script>

ZenBlog/Views/Shared/_Styles.cshtml
<!-- Favicons -->
<link href="/Blog Template/assets/img/favicon.png" rel="icon">
<link href="/Blog Template/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="/Blog Template/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/Blog Template/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
<link href="/Blog Template/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
<link href="/Blog Template/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
<link href="/Blog Template/assets/vendor/aos/aos.css" rel="stylesheet">

<!-- Template Main CSS Files -->
<link href="/Blog Template/assets/css/variables.css" rel="stylesheet">
<link href="/Blog Template/assets/css/main.css" rel="stylesheet">
<link href="/css/custom.css" rel="stylesheet" />