ZenBlog/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZenBlog.Core.Repositories;
using ZenBlog.DataLayer.Models;

namespace ZenBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        // GET: CategoryController
        public async Task<ActionResult> Index()
        {
            return View(await _categoryRepository.GetAllCategoryAsync());
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            await _categoryRepository.Insert(category);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _categoryRepository.GetCategoryByIdAsync(id));
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            await _categoryRepository.Update(category);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _categoryRepository.GetCategoryByIdAsync(id));
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(float id)
        {
            await _categoryRepository.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ZenBlog/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ZenBlog.Core.DTOs;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private IPostRepository _postRepository;
        private ICategoryRepository _categoryRepository;
        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
        }

        // GET: PostController
        [Route("Admin/Posts/{pageNumber?}")]
        public async Task<ActionResult> Index(int pageNumber = 0, int pageSize = 5)
        {
            ViewData["pageNumber"] = pageNumber;
            return View(await _postRepository.GetAllPost(pageNumber, pageSize));
        }

        // GET: PostController/Details/5
        //public async Task<ActionResult> Details(int id)
        //{
        //    return View(await _postRepository.GetPostById(id));
        //}

        // GET: PostController/Create
        public async Task<ActionResult> Create()
        {
            var categories = await _categoryRepository.GetAllCategoryAsync();
            return View(new AddEditPostViewModel()
            {
                Category = categories
            });
        }

        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddEditPostViewModel addEditPost)
        {
            if (!ModelState.IsValid)
            {
                return View(addEditPost);
            }
            addEditPost.UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            await _postRepository.Insert(addEditPost);
            return RedirectToAction(nameof(Index));
        }

        // GET: PostController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _postRepository.GetPostForUpdate(id));
        }

        // POST: PostController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AddEditPostViewModel addEditPost)
        {
            if (!ModelState.IsValid)
            {
                return View(addEditPost);
            }
            await _postRepository.Update(addEditPost);
            return RedirectToAction(nameof(Index));
        }

        // GET: PostController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _postRepository.GetPostById(id));
        }

        // POST: PostController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(float id)
        {
            await _postRepository.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ZenBlog/Areas/Teacher/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZenBlog.Core.Repositories;
using ZenBlog.DataLayer.Models;

namespace ZenBlog.Areas.Teacher.Controllers
{
    [Area("Teacher")]
    public class CategoryController : Controller
    {
        private ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        // GET: CategoryController
        public async Task<ActionResult> Index()
        {
            return View(await _categoryRepository.GetAllCategoryAsync());
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            await _categoryRepository.Insert(category);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _categoryRepository.GetCategoryByIdAsync(id));
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            await _categoryRepository.Update(category);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _categoryRepository.GetCategoryByIdAsync(id));
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(float id)
        {
            await _categoryRepository.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ZenBlog/Components/ShowCategoryViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Components
{
    public class ShowCategoryViewComponent : ViewComponent
    {
        private ICategoryRepository _categoryRepository;

        public ShowCategoryViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryRepository.GetAllCategoryAsync();
            return View("/Views/Components/ShowCategoryViewComponent.cshtml", categories);
        }
    }
}

ZenBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZenBlog.Core.Repositories;

namespace ZenBlog.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        [Route("Category/{categoryTitle}/{categoryId}/{pageNumber?}")]
        public async Task<IActionResult> ShowCategory(string categoryTitle, int categoryId, int pageNumber = 0, int pageSize = 5)
        {
            ViewData["categoryTitle"] = categoryTitle;
            var result = await _categoryRepository
                .GetCategory(categoryId, pageNumber, pageSize);
            return View(result);
        }
    }
}

ZenBlog/Views/Category/ShowCategory.cshtml
@model GetCategoryViewModel
@{
    ViewData["Title"] = "نمایش گروه";
}

<main id="main">
    <section>
        <div class="container">
            <div class="row">

                <div class="col-md-9 aos-init aos-animate" data-aos="fade-up">
                    <h3 class="category-title">گروه: @ViewData["categoryTitle"]</h3>

                    @if (Model.Posts.Count() <= 0)
                    {

                        <div class="alert alert-info d-flex align-items-center" role="alert">
                            <svg class="bi flex-shrink-0 me-2 mx-3" width="24" height="24" role="img" aria-label="Warning:">
                                <use xlink:href="#exclamation-triangle-fill">
                                    <template shadowmode="closed">
                                        <svg id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
                                        </svg>
                                    </template>
                                </use>
                            </svg>
                            <div>
                                برای این گروه هنوز هیچ پستی اضافه نشده است
                            </div>
                            @*<button type="button" class="btn-close mx-3" data-bs-dismiss="alert" aria-label="Close"></button>*@
                        </div>
                    }

                    @foreach (var post in Model.Posts)
                    {
                        <div class="d-md-flex post-entry-2 half">
                            <a asp-controller="Post"
                               asp-action="Post"
                               asp-route-postId="@post.Id"
                               asp-route-postTitle="@post.Title"
                               asp-route-categoryTitle="@ViewData["categoryTitle"]"
                               class="ms-4 thumbnail">
                                <img src="@post.Image" alt="@post.Title" class="img-fluid">
                            </a>
                            <div>
                                <div class="post-meta"><span class="date">@ViewData["categoryTitle"]</span> <span class="mx-1">•</span> <span>Jul 5th '22</span></div>
                                <h3>
                                    <a asp-controller="Post"
                                       asp-action="Post"
                                       asp-route-postId="@post.Id"
                                       asp-route-postTitle="@post.Title"
                                       asp-route-categoryTitle="@ViewData["categoryTitle"]">@post.Title</a>
                                </h3>
                                <p>
                                    @post.ShortDescription
                                </p>
                                <div class="d-flex align-items-center author">
                                    <div class="photo"><img src="@post.User.Image" alt="@post.User.FullName" class="img-fluid"></div>
                                    <div class="name">
                                        <h3 class="me-2 p-0">@post.User.FullName</h3>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }



                    <div class="text-start py-4">
                        <div class="custom-pagination">
                            @*<a href="#" class="prev">Prevous</a>*@
                            @for (int i = 0; i <= Model.PostCount; i++)
                            {
                                <a asp-action="ShowCategory"
                                   asp-route-pageNumber="@i"
                                   class="active">@(i+1)</a>
                            }
                            @*<a href="#" class="next">Next</a>*@
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- ======= Sidebar ======= -->
                    <div class="aside-block">

                        <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">جدیدترین ها</button>
                            </li>
                        </ul>

                        <div class="tab-content" id="pills-tabContent">

                            <!-- Popular -->
                            <div class="tab-pane fade active show" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">

                                <div class="post-entry-1 border-bottom">
                                    <div class="post-meta"><span class="date">Sport</span> <span class="mx-1">•</span> <span>Jul 5th '22</span></div>
                                    <h2 class="mb-2"><a href="#">How to Avoid Distraction and Stay Focused During Video Calls?</a></h2>
                                    <span class="author mb-3 d-block">Jenny Wilson</span>
                                </div>


                            </div> <!-- End Popular -->

                        </div>
                    </div>

                    @await Component.InvokeAsync("ShowCategory")
                    <!--<div class="aside-block">
                        <h3 class="aside-title">Tags</h3>
                        <ul class="aside-tags list-unstyled">
                            <li><a href="category.html">Business</a></li>
                            <li><a href="category.html">Culture</a></li>
                            <li><a href="category.html">Sport</a></li>
                            <li><a href="category.html">Food</a></li>
                            <li><a href="category.html">Politics</a></li>
                            <li><a href="category.html">Celebrity</a></li>
                            <li><a href="category.html">Startups</a></li>
                            <li><a href="category.html">Travel</a></li>
                        </ul>
                    </div>-->
                    <!-- End Tags -->

                </div>

            </div>
        </div>
    </section>
</main>